spring.application.name=learn-spring


spring.profiles.active=dev

user-control.url=http://google.com
user-control.username=sameer
user-control.key=jelly@123

management.endpoints.web.exposure.include=health,beans,metrics,caches